"""The RouteSpec inventory: one entry per live (method, path) the server
dispatches (#202 step 1).

INERT BY CONSTRUCTION. Nothing in ``server.py`` imports this module, and this
step changes no response. The registry exists so the LATER steps of #202 have
one declared place to enforce from, and so CI can already refuse two kinds of
drift today:

  UNCLASSIFIED — a live dispatch branch with no ``RouteSpec``
  DEAD         — a ``RouteSpec`` matching no live dispatch branch

Both are decided against the DISPATCH ITSELF, not against another hand-written
list: ``route_extract.py`` parses ``server.py`` with ``ast`` and reports the
branches it actually contains, and ``tests/test_route_registry.py`` compares
the two sets. A registry checked against a transcription would only prove that
two prose lists agree.

Identity: ``template``
----------------------
Each spec carries BOTH

  ``pattern``   the full-path regex, faithful to what the dispatch tests
                (``assign-\\w+`` stays ``\\w+``, not the looser ``[^/]+``); this
                is what a policy engine will match a real request path against;
  ``template``  the canonical shape — ``{}`` for one path segment, ``{*}`` for
                a free tail — which is the key both sides can derive, so the
                gate compares templates and separately proves that each
                ``pattern`` expands to exactly its own ``template``.

What is NOT here
----------------
* ``_GET_ROUTES`` / ``_POST_ROUTES`` / ``CONTEXT_SCOPED_READ_ROUTES`` in
  ``server.py`` still exist and are still the code paths that run. This step
  only CROSS-CHECKS them against this registry (see the gate); removing them is
  a later step.
* ``auth`` and ``scope_axis`` are declared slots for that later work and are
  ``UNCLASSIFIED`` on every entry. They are deliberately NOT filled in with
  guesses: a half-populated policy field reads as authority and would be
  believed. Nothing reads either field.
* The two UNCONDITIONAL tails of the dispatch are not branches and so have no
  spec: ``_dispatch_get`` ends by handing any non-``/api/`` path to
  ``_serve_static`` (which serves a file from ``static/`` or 404s), and
  ``do_POST`` ends in ``_unmatched_route("POST")``. The ``if`` branches INSIDE
  ``_serve_static`` (the ``/setup`` and ``/`` shells) do appear, as
  ``kind="static"``.

Reading a POST entry
--------------------
``do_POST`` refuses anything ``_supported_methods`` (i.e. ``_POST_ROUTES``)
does not admit BEFORE the dispatch chain runs, so a POST spec here describes a
branch that exists in the dispatch — not, on its own, a path that answers. The
gate's cross-check reports where the two disagree.
"""
from dataclasses import dataclass

#: Value of a classification slot no one has filled in yet. Read by nothing.
UNCLASSIFIED = "unclassified"


@dataclass(frozen=True)
class RouteSpec:
    """One live (method, path-pattern) the dispatch selects.

    method   ``GET`` or ``POST`` — the two verbs with a dispatch chain. HEAD
             mirrors GET through ``do_GET``; PUT/PATCH/DELETE/OPTIONS answer
             from ``_supported_methods`` and select no route of their own.
    pattern  full-path regex, faithful to the dispatch's own test.
    template ``{}``/``{*}`` canonical shape — the identity the gate compares.
    name     stable identifier, derived from the path so it stays stable while
             the path does.
    handler  the ``Handler`` method whose body holds the branch (verified
             against the extractor, so it cannot rot into decoration).
    kind     structural: ``route`` (a resource), ``family`` (a branch broader
             than the real routes under it), ``fallthrough`` (an answer for
             paths no route claimed) or ``static`` (a file/shell).
    auth / scope_axis
             INERT slots for a later step of #202. Nothing reads them.
    note     free text; provenance for the odd entries.
    """

    method: str
    pattern: str
    template: str
    name: str
    handler: str
    kind: str = "route"
    auth: str = UNCLASSIFIED
    scope_axis: str = UNCLASSIFIED
    note: str = ""

    @property
    def key(self) -> tuple:
        return (self.method, self.template)


REGISTRY = (

    # -- GET ---------------------------------------------------------------
    RouteSpec("GET", r"^$", "", "get_empty_path", "_serve_static",
              kind="static",
              note=("unreachable over HTTP — a request line always "
                    "carries at least '/'; listed because the branch "
                    "exists")),
    RouteSpec("GET", r"^/$", "/", "get_index", "_serve_static", kind="static"),
    RouteSpec("GET", r"^/api/accounts$", "/api/accounts", "get_accounts",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/accounts/[^/]+/sessions$",
              "/api/accounts/{}/sessions", "get_accounts_id_sessions",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/auth/accounts$", "/api/auth/accounts",
              "get_auth_accounts", "_dispatch_get"),
    RouteSpec("GET", r"^/api/auth/me$", "/api/auth/me", "get_auth_me",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/auth/roles$", "/api/auth/roles",
              "get_auth_roles", "_dispatch_get"),
    RouteSpec("GET", r"^/api/bootstrap/status$", "/api/bootstrap/status",
              "get_bootstrap_status", "_dispatch_get"),
    RouteSpec("GET", r"^/api/calendar-feeds$", "/api/calendar-feeds",
              "get_calendar_feeds", "_dispatch_get"),
    RouteSpec("GET", r"^/api/context$", "/api/context", "get_context",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/context/options$", "/api/context/options",
              "get_context_options", "_dispatch_get"),
    RouteSpec("GET", r"^/api/demo/overview$", "/api/demo/overview",
              "get_demo_overview", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+$", "/api/games/{}", "get_games_id",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/availability-summary$",
              "/api/games/{}/availability-summary",
              "get_games_id_availability_summary", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/board$", "/api/games/{}/board",
              "get_games_id_board", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/lineups$", "/api/games/{}/lineups",
              "get_games_id_lineups", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/officials$",
              "/api/games/{}/officials", "get_games_id_officials",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/reschedule$",
              "/api/games/{}/reschedule", "get_games_id_reschedule",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/roster$", "/api/games/{}/roster",
              "get_games_id_roster", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/roster-status$",
              "/api/games/{}/roster-status", "get_games_id_roster_status",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/substitute-addable$",
              "/api/games/{}/substitute-addable",
              "get_games_id_substitute_addable", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/substitute-candidates$",
              "/api/games/{}/substitute-candidates",
              "get_games_id_substitute_candidates", "_dispatch_get"),
    RouteSpec("GET", r"^/api/games/[^/]+/substitutes$",
              "/api/games/{}/substitutes", "get_games_id_substitutes",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/guardians/links$", "/api/guardians/links",
              "get_guardians_links", "_dispatch_get"),
    RouteSpec("GET", r"^/api/health$", "/api/health", "get_health",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/import/hierarchy-codes$",
              "/api/import/hierarchy-codes", "get_import_hierarchy_codes",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/me/assignments$", "/api/me/assignments",
              "get_me_assignments", "_dispatch_get"),
    RouteSpec("GET", r"^/api/me/guardian/home$", "/api/me/guardian/home",
              "get_me_guardian_home", "_dispatch_get"),
    RouteSpec("GET",
              r"^/api/me/guardian/[^/]+/substitute-opportunities/[^/]+$",
              "/api/me/guardian/{}/substitute-opportunities/{}",
              "get_me_guardian_id_substitute_opportunities_id",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/me/player-home$", "/api/me/player-home",
              "get_me_player_home", "_dispatch_get"),
    RouteSpec("GET", r"^/api/me/substitute-opportunities/[^/]+$",
              "/api/me/substitute-opportunities/{}",
              "get_me_substitute_opportunities_id", "_dispatch_get"),
    RouteSpec("GET", r"^/api/notifications$", "/api/notifications",
              "get_notifications", "_dispatch_get"),
    RouteSpec("GET", r"^/api/notifications/contacts$",
              "/api/notifications/contacts", "get_notifications_contacts",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/notifications/deliveries$",
              "/api/notifications/deliveries", "get_notifications_deliveries",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/notifications/device-tokens$",
              "/api/notifications/device-tokens",
              "get_notifications_device_tokens", "_dispatch_get"),
    RouteSpec("GET", r"^/api/notifications/preferences$",
              "/api/notifications/preferences",
              "get_notifications_preferences", "_dispatch_get"),
    RouteSpec("GET", r"^/api/officials$", "/api/officials", "get_officials",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/officials/[^/]+/availability$",
              "/api/officials/{}/availability",
              "get_officials_id_availability", "_dispatch_get"),
    RouteSpec("GET", r"^/api/onboarding/status$", "/api/onboarding/status",
              "get_onboarding_status", "_dispatch_get"),
    RouteSpec("GET", r"^/api/players$", "/api/players", "get_players",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/public/games/[^/]+$", "/api/public/games/{}",
              "get_public_games_id", "_dispatch_get"),
    RouteSpec("GET", r"^/api/public/schedule$", "/api/public/schedule",
              "get_public_schedule", "_dispatch_get"),
    RouteSpec("GET", r"^/api/public/standings/league-season/[^/]+/[^/]+$",
              "/api/public/standings/league-season/{}/{}",
              "get_public_standings_league_season_id_id", "_dispatch_get"),
    RouteSpec("GET", r"^/api/public/standings/[^/]+$",
              "/api/public/standings/{}", "get_public_standings_id",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/readiness$", "/api/readiness", "get_readiness",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/reschedule/pending$", "/api/reschedule/pending",
              "get_reschedule_pending", "_dispatch_get"),
    RouteSpec("GET", r"^/api/scheduler/drafts$", "/api/scheduler/drafts",
              "get_scheduler_drafts", "_dispatch_get"),
    RouteSpec("GET", r"^/api/scheduler/scenarios$",
              "/api/scheduler/scenarios", "get_scheduler_scenarios",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/scheduler/scenarios/[^/]+$",
              "/api/scheduler/scenarios/{}", "get_scheduler_scenarios_id",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/setup/hierarchy$", "/api/setup/hierarchy",
              "get_setup_hierarchy", "_dispatch_get"),
    RouteSpec("GET", r"^/api/setup/leagues/[^/]+/teams$",
              "/api/setup/leagues/{}/teams", "get_setup_leagues_id_teams",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/setup/scheduling-policy$",
              "/api/setup/scheduling-policy", "get_setup_scheduling_policy",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/setup/seasons/[^/]+/team-registrations$",
              "/api/setup/seasons/{}/team-registrations",
              "get_setup_seasons_id_team_registrations", "_dispatch_get"),
    RouteSpec("GET", r"^/api/standings/league-season/[^/]+/[^/]+$",
              "/api/standings/league-season/{}/{}",
              "get_standings_league_season_id_id", "_dispatch_get"),
    RouteSpec("GET", r"^/api/standings/[^/]+$", "/api/standings/{}",
              "get_standings_id", "_dispatch_get"),
    RouteSpec("GET", r"^/api/status$", "/api/status", "get_status",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/onboarding/status$",
              "/api/v2/onboarding/status", "get_v2_onboarding_status",
              "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/hierarchy$", "/api/v2/setup/hierarchy",
              "get_v2_setup_hierarchy", "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/overview$", "/api/v2/setup/overview",
              "get_v2_setup_overview", "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/programs/[^/]+/teams$",
              "/api/v2/setup/programs/{}/teams",
              "get_v2_setup_programs_id_teams", "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/progress$", "/api/v2/setup/progress",
              "get_v2_setup_progress", "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/seasons/[^/]+/team-registrations$",
              "/api/v2/setup/seasons/{}/team-registrations",
              "get_v2_setup_seasons_id_team_registrations", "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/seasons/[^/]+/venue-access$",
              "/api/v2/setup/seasons/{}/venue-access",
              "get_v2_setup_seasons_id_venue_access", "_dispatch_get"),
    RouteSpec("GET", r"^/api/v2/setup/seasons/[^/]+/venue-candidates$",
              "/api/v2/setup/seasons/{}/venue-candidates",
              "get_v2_setup_seasons_id_venue_candidates", "_dispatch_get"),
    RouteSpec("GET", r"^/api/.*$", "/api/{*}", "get_api_unmatched",
              "_dispatch_get", kind="fallthrough",
              note=("no resource: the tail that answers 405 (known "
                    "path, wrong method) or 404 for anything under "
                    "/api/")),
    RouteSpec("GET", r"^/calendar/division/[^/]+\.ics$",
              "/calendar/division/{}.ics", "get_calendar_division_id_ics",
              "_dispatch_get"),
    RouteSpec("GET", r"^/calendar/official/[^/]+\.ics$",
              "/calendar/official/{}.ics", "get_calendar_official_id_ics",
              "_dispatch_get"),
    RouteSpec("GET", r"^/calendar/player/[^/]+\.ics$",
              "/calendar/player/{}.ics", "get_calendar_player_id_ics",
              "_dispatch_get"),
    RouteSpec("GET", r"^/calendar/team/[^/]+\.ics$", "/calendar/team/{}.ics",
              "get_calendar_team_id_ics", "_dispatch_get"),
    RouteSpec("GET", r"^/favicon\.ico$", "/favicon.ico", "get_favicon_ico",
              "_dispatch_get"),
    RouteSpec("GET", r"^/mobile$", "/mobile", "get_mobile_shell",
              "_serve_static", kind="static"),
    RouteSpec("GET", r"^/mobile/$", "/mobile/", "get_mobile_shell_slash",
              "_serve_static", kind="static"),
    RouteSpec("GET", r"^/setup$", "/setup", "get_setup_shell",
              "_serve_static", kind="static"),
    RouteSpec("GET", r"^/setup/$", "/setup/", "get_setup_shell_slash",
              "_serve_static", kind="static"),

    # -- POST --------------------------------------------------------------
    RouteSpec("POST", r"^/api/accounts$", "/api/accounts", "post_accounts",
              "do_POST"),
    RouteSpec("POST", r"^/api/accounts/[^/]+/active$",
              "/api/accounts/{}/active", "post_accounts_id_active", "do_POST"),
    RouteSpec("POST", r"^/api/accounts/[^/]+/scope$",
              "/api/accounts/{}/scope", "post_accounts_id_scope", "do_POST"),
    RouteSpec("POST", r"^/api/accounts/[^/]+/sessions/[^/]+/revoke$",
              "/api/accounts/{}/sessions/{}/revoke",
              "post_accounts_id_sessions_id_revoke", "do_POST"),
    RouteSpec("POST", r"^/api/admin/factory-reset/execute$",
              "/api/admin/factory-reset/execute",
              "post_admin_factory_reset_execute", "do_POST"),
    RouteSpec("POST", r"^/api/admin/factory-reset/preview$",
              "/api/admin/factory-reset/preview",
              "post_admin_factory_reset_preview", "do_POST"),
    RouteSpec("POST", r"^/api/auth/login$", "/api/auth/login",
              "post_auth_login", "do_POST"),
    RouteSpec("POST", r"^/api/auth/logout$", "/api/auth/logout",
              "post_auth_logout", "do_POST"),
    RouteSpec("POST", r"^/api/bootstrap/claim$", "/api/bootstrap/claim",
              "post_bootstrap_claim", "do_POST"),
    RouteSpec("POST", r"^/api/calendar-feeds$", "/api/calendar-feeds",
              "post_calendar_feeds", "do_POST"),
    RouteSpec("POST", r"^/api/calendar-feeds/[^/]+/revoke$",
              "/api/calendar-feeds/{}/revoke",
              "post_calendar_feeds_id_revoke", "do_POST"),
    RouteSpec("POST", r"^/api/context$", "/api/context", "post_context",
              "do_POST"),
    RouteSpec("POST", r"^/api/demo/add-ice-slot$", "/api/demo/add-ice-slot",
              "post_demo_add_ice_slot", "do_POST"),
    RouteSpec("POST", r"^/api/demo/clear$", "/api/demo/clear",
              "post_demo_clear", "do_POST"),
    RouteSpec("POST", r"^/api/demo/load$", "/api/demo/load", "post_demo_load",
              "do_POST"),
    RouteSpec("POST", r"^/api/demo/reset$", "/api/demo/reset",
              "post_demo_reset", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/availability$",
              "/api/games/{}/availability", "post_games_id_availability",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/availability/remind$",
              "/api/games/{}/availability/remind",
              "post_games_id_availability_remind", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/build-roster$",
              "/api/games/{}/build-roster", "post_games_id_build_roster",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/cancel$", "/api/games/{}/cancel",
              "post_games_id_cancel", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/move$", "/api/games/{}/move",
              "post_games_id_move", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/officials/assign$",
              "/api/games/{}/officials/assign",
              "post_games_id_officials_assign", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/publish$", "/api/games/{}/publish",
              "post_games_id_publish", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/reschedule/request$",
              "/api/games/{}/reschedule/request",
              "post_games_id_reschedule_request", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/reschedule/[^/]+/decide$",
              "/api/games/{}/reschedule/{}/decide",
              "post_games_id_reschedule_id_decide", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/reschedule/[^/]+/respond$",
              "/api/games/{}/reschedule/{}/respond",
              "post_games_id_reschedule_id_respond", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/result$", "/api/games/{}/result",
              "post_games_id_result", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/result/approve$",
              "/api/games/{}/result/approve", "post_games_id_result_approve",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/roster/copy-previous$",
              "/api/games/{}/roster/copy-previous",
              "post_games_id_roster_copy_previous", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/roster/lock$",
              "/api/games/{}/roster/lock", "post_games_id_roster_lock",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/roster/remove$",
              "/api/games/{}/roster/remove", "post_games_id_roster_remove",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/roster/select$",
              "/api/games/{}/roster/select", "post_games_id_roster_select",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/roster/unlock$",
              "/api/games/{}/roster/unlock", "post_games_id_roster_unlock",
              "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/add-candidate$",
              "/api/games/{}/substitutes/add-candidate",
              "post_games_id_substitutes_add_candidate", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/enroll$",
              "/api/games/{}/substitutes/enroll",
              "post_games_id_substitutes_enroll", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/withdraw$",
              "/api/games/{}/substitutes/withdraw",
              "post_games_id_substitutes_withdraw", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/[^/]+/accept$",
              "/api/games/{}/substitutes/{}/accept",
              "post_games_id_substitutes_id_accept", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/[^/]+/add-to-roster$",
              "/api/games/{}/substitutes/{}/add-to-roster",
              "post_games_id_substitutes_id_add_to_roster", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/[^/]+/decline$",
              "/api/games/{}/substitutes/{}/decline",
              "post_games_id_substitutes_id_decline", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/substitutes/[^/]+/offer$",
              "/api/games/{}/substitutes/{}/offer",
              "post_games_id_substitutes_id_offer", "do_POST"),
    RouteSpec("POST", r"^/api/games/[^/]+/.+$", "/api/games/{}/{*}",
              "post_games_id_action", "do_POST", kind="family",
              note=("the family regex; every real action is a sibling "
                    "spec below it")),
    RouteSpec("POST", r"^/api/guardians/links$", "/api/guardians/links",
              "post_guardians_links", "do_POST"),
    RouteSpec("POST", r"^/api/guardians/links/[^/]+/verify$",
              "/api/guardians/links/{}/verify",
              "post_guardians_links_id_verify", "do_POST"),
    RouteSpec("POST", r"^/api/import/commit/officials-availability$",
              "/api/import/commit/officials-availability",
              "post_import_commit_officials_availability", "do_POST"),
    RouteSpec("POST", r"^/api/import/commit/rinks-ice-slots$",
              "/api/import/commit/rinks-ice-slots",
              "post_import_commit_rinks_ice_slots", "do_POST"),
    RouteSpec("POST", r"^/api/import/commit/teams-players$",
              "/api/import/commit/teams-players",
              "post_import_commit_teams_players", "do_POST"),
    RouteSpec("POST", r"^/api/import/dry-run$", "/api/import/dry-run",
              "post_import_dry_run", "do_POST"),
    RouteSpec("POST", r"^/api/me/guardian/[^/]+/games/[^/]+/availability$",
              "/api/me/guardian/{}/games/{}/availability",
              "post_me_guardian_id_games_id_availability", "do_POST"),
    RouteSpec("POST",
              r"^/api/me/guardian/[^/]+/substitute-opportunities/[^/]+/accept-offer$",
              "/api/me/guardian/{}/substitute-opportunities/{}/accept-offer",
              "post_me_guardian_id_substitute_opportunities_id_accept_offer",
              "do_POST"),
    RouteSpec("POST",
              r"^/api/me/guardian/[^/]+/substitute-opportunities/[^/]+/decline-offer$",
              "/api/me/guardian/{}/substitute-opportunities/{}/decline-offer",
              "post_me_guardian_id_substitute_opportunities_id_decline_offer",
              "do_POST"),
    RouteSpec("POST",
              r"^/api/me/substitute-opportunities/[^/]+/accept-offer$",
              "/api/me/substitute-opportunities/{}/accept-offer",
              "post_me_substitute_opportunities_id_accept_offer", "do_POST"),
    RouteSpec("POST",
              r"^/api/me/substitute-opportunities/[^/]+/decline-offer$",
              "/api/me/substitute-opportunities/{}/decline-offer",
              "post_me_substitute_opportunities_id_decline_offer", "do_POST"),
    RouteSpec("POST", r"^/api/me/substitute-opportunities/[^/]+/enroll$",
              "/api/me/substitute-opportunities/{}/enroll",
              "post_me_substitute_opportunities_id_enroll", "do_POST"),
    RouteSpec("POST", r"^/api/me/substitute-opportunities/[^/]+/withdraw$",
              "/api/me/substitute-opportunities/{}/withdraw",
              "post_me_substitute_opportunities_id_withdraw", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/contacts$",
              "/api/notifications/contacts", "post_notifications_contacts",
              "do_POST"),
    RouteSpec("POST", r"^/api/notifications/contacts/[^/]+/active$",
              "/api/notifications/contacts/{}/active",
              "post_notifications_contacts_id_active", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/deliveries/process$",
              "/api/notifications/deliveries/process",
              "post_notifications_deliveries_process", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/deliveries/[^/]+/ignore$",
              "/api/notifications/deliveries/{}/ignore",
              "post_notifications_deliveries_id_ignore", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/deliveries/[^/]+/retry$",
              "/api/notifications/deliveries/{}/retry",
              "post_notifications_deliveries_id_retry", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/device-tokens$",
              "/api/notifications/device-tokens",
              "post_notifications_device_tokens", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/device-tokens/[^/]+/active$",
              "/api/notifications/device-tokens/{}/active",
              "post_notifications_device_tokens_id_active", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/preferences$",
              "/api/notifications/preferences",
              "post_notifications_preferences", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/preferences/[^/]+/active$",
              "/api/notifications/preferences/{}/active",
              "post_notifications_preferences_id_active", "do_POST"),
    RouteSpec("POST", r"^/api/notifications/read-all$",
              "/api/notifications/read-all", "post_notifications_read_all",
              "do_POST"),
    RouteSpec("POST", r"^/api/notifications/[^/]+/read$",
              "/api/notifications/{}/read", "post_notifications_id_read",
              "do_POST"),
    RouteSpec("POST", r"^/api/officials/assignments/[^/]+/accept$",
              "/api/officials/assignments/{}/accept",
              "post_officials_assignments_id_accept", "do_POST"),
    RouteSpec("POST", r"^/api/officials/assignments/[^/]+/decline$",
              "/api/officials/assignments/{}/decline",
              "post_officials_assignments_id_decline", "do_POST"),
    RouteSpec("POST", r"^/api/officials/assignments/[^/]+/unassign$",
              "/api/officials/assignments/{}/unassign",
              "post_officials_assignments_id_unassign", "do_POST"),
    RouteSpec("POST", r"^/api/officials/availability/[^/]+/delete$",
              "/api/officials/availability/{}/delete",
              "post_officials_availability_id_delete", "do_POST"),
    RouteSpec("POST", r"^/api/officials/[^/]+/availability$",
              "/api/officials/{}/availability",
              "post_officials_id_availability", "do_POST"),
    RouteSpec("POST", r"^/api/public/calendar-feeds$",
              "/api/public/calendar-feeds", "post_public_calendar_feeds",
              "do_POST"),
    RouteSpec("POST", r"^/api/reset$", "/api/reset", "post_reset", "do_POST"),
    RouteSpec("POST", r"^/api/scheduler/commit$", "/api/scheduler/commit",
              "post_scheduler_commit", "do_POST"),
    RouteSpec("POST", r"^/api/scheduler/draft$", "/api/scheduler/draft",
              "post_scheduler_draft", "do_POST"),
    RouteSpec("POST", r"^/api/scheduler/drafts/discard$",
              "/api/scheduler/drafts/discard",
              "post_scheduler_drafts_discard", "do_POST"),
    RouteSpec("POST", r"^/api/scheduler/drafts/publish$",
              "/api/scheduler/drafts/publish",
              "post_scheduler_drafts_publish", "do_POST"),
    RouteSpec("POST", r"^/api/scheduler/scenarios$",
              "/api/scheduler/scenarios", "post_scheduler_scenarios",
              "do_POST"),
    RouteSpec("POST", r"^/api/scheduler/scenarios/[^/]+/commit$",
              "/api/scheduler/scenarios/{}/commit",
              "post_scheduler_scenarios_id_commit", "do_POST"),
    RouteSpec("POST", r"^/api/setup/club$", "/api/setup/club",
              "post_setup_club", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/club/[^/]+/delete$",
              "/api/setup/club/{}/delete", "post_setup_club_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/division$", "/api/setup/division",
              "post_setup_division", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/division/[^/]+/assign-\w+$",
              "/api/setup/division/{}/assign-{}",
              "post_setup_division_id_assign_target", "_handle_setup",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/setup/division/[^/]+/delete$",
              "/api/setup/division/{}/delete",
              "post_setup_division_id_delete", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/game$", "/api/setup/game",
              "post_setup_game", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/game/[^/]+/delete$",
              "/api/setup/game/{}/delete", "post_setup_game_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/ice-availability/commit$",
              "/api/setup/ice-availability/commit",
              "post_setup_ice_availability_commit", "do_POST"),
    RouteSpec("POST", r"^/api/setup/ice-availability/preview$",
              "/api/setup/ice-availability/preview",
              "post_setup_ice_availability_preview", "do_POST"),
    RouteSpec("POST", r"^/api/setup/ice-slot$", "/api/setup/ice-slot",
              "post_setup_ice_slot", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/ice-slot/[^/]+/delete$",
              "/api/setup/ice-slot/{}/delete",
              "post_setup_ice_slot_id_delete", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/league$", "/api/setup/league",
              "post_setup_league", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/league/[^/]+/assign-\w+$",
              "/api/setup/league/{}/assign-{}",
              "post_setup_league_id_assign_target", "_handle_setup",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/setup/league/[^/]+/delete$",
              "/api/setup/league/{}/delete", "post_setup_league_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/level$", "/api/setup/level",
              "post_setup_level", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/level/[^/]+/delete$",
              "/api/setup/level/{}/delete", "post_setup_level_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/official$", "/api/setup/official",
              "post_setup_official", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/official/[^/]+/delete$",
              "/api/setup/official/{}/delete",
              "post_setup_official_id_delete", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/organization$", "/api/setup/organization",
              "post_setup_organization", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/organization/[^/]+/delete$",
              "/api/setup/organization/{}/delete",
              "post_setup_organization_id_delete", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/player$", "/api/setup/player",
              "post_setup_player", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/player/[^/]+/assign-\w+$",
              "/api/setup/player/{}/assign-{}",
              "post_setup_player_id_assign_target", "_handle_setup",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/setup/player/[^/]+/delete$",
              "/api/setup/player/{}/delete", "post_setup_player_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/rink$", "/api/setup/rink",
              "post_setup_rink", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/rink/[^/]+/assign-\w+$",
              "/api/setup/rink/{}/assign-{}",
              "post_setup_rink_id_assign_target", "_handle_setup",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/setup/rink/[^/]+/delete$",
              "/api/setup/rink/{}/delete", "post_setup_rink_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/scheduling-policy$",
              "/api/setup/scheduling-policy", "post_setup_scheduling_policy",
              "do_POST"),
    RouteSpec("POST", r"^/api/setup/season$", "/api/setup/season",
              "post_setup_season", "_handle_setup"),
    RouteSpec("POST",
              r"^/api/setup/season-team-registration/[^/]+/assign-division$",
              "/api/setup/season-team-registration/{}/assign-division",
              "post_setup_season_team_registration_id_assign_division",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/season-team-registration/[^/]+/remove$",
              "/api/setup/season-team-registration/{}/remove",
              "post_setup_season_team_registration_id_remove",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/season/[^/]+/delete$",
              "/api/setup/season/{}/delete", "post_setup_season_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/seasons/[^/]+/roll-forward$",
              "/api/setup/seasons/{}/roll-forward",
              "post_setup_seasons_id_roll_forward", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/seasons/[^/]+/team-registrations$",
              "/api/setup/seasons/{}/team-registrations",
              "post_setup_seasons_id_team_registrations", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/team$", "/api/setup/team",
              "post_setup_team", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/team/[^/]+/assign-\w+$",
              "/api/setup/team/{}/assign-{}",
              "post_setup_team_id_assign_target", "_handle_setup",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/setup/team/[^/]+/delete$",
              "/api/setup/team/{}/delete", "post_setup_team_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/venue$", "/api/setup/venue",
              "post_setup_venue", "_handle_setup"),
    RouteSpec("POST", r"^/api/setup/venue/[^/]+/assign-\w+$",
              "/api/setup/venue/{}/assign-{}",
              "post_setup_venue_id_assign_target", "_handle_setup",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/setup/venue/[^/]+/delete$",
              "/api/setup/venue/{}/delete", "post_setup_venue_id_delete",
              "_handle_setup"),
    RouteSpec("POST", r"^/api/v2/setup/club$", "/api/v2/setup/club",
              "post_v2_setup_club", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/club/[^/]+/delete$",
              "/api/v2/setup/club/{}/delete", "post_v2_setup_club_id_delete",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/division$", "/api/v2/setup/division",
              "post_v2_setup_division", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/division/[^/]+/assign-\w+$",
              "/api/v2/setup/division/{}/assign-{}",
              "post_v2_setup_division_id_assign_target", "_handle_setup_v2",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/v2/setup/division/[^/]+/delete$",
              "/api/v2/setup/division/{}/delete",
              "post_v2_setup_division_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/game$", "/api/v2/setup/game",
              "post_v2_setup_game", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/game/[^/]+/delete$",
              "/api/v2/setup/game/{}/delete", "post_v2_setup_game_id_delete",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/ice-slot$", "/api/v2/setup/ice-slot",
              "post_v2_setup_ice_slot", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/ice-slot/[^/]+/delete$",
              "/api/v2/setup/ice-slot/{}/delete",
              "post_v2_setup_ice_slot_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/league$", "/api/v2/setup/league",
              "post_v2_setup_league", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/league-season/[^/]+/delete$",
              "/api/v2/setup/league-season/{}/delete",
              "post_v2_setup_league_season_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/league/[^/]+/delete$",
              "/api/v2/setup/league/{}/delete",
              "post_v2_setup_league_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/official$", "/api/v2/setup/official",
              "post_v2_setup_official", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/official/[^/]+/delete$",
              "/api/v2/setup/official/{}/delete",
              "post_v2_setup_official_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/organization$",
              "/api/v2/setup/organization", "post_v2_setup_organization",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/organization/[^/]+/delete$",
              "/api/v2/setup/organization/{}/delete",
              "post_v2_setup_organization_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/player$", "/api/v2/setup/player",
              "post_v2_setup_player", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/player/[^/]+/active$",
              "/api/v2/setup/player/{}/active",
              "post_v2_setup_player_id_active", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/player/[^/]+/assign-\w+$",
              "/api/v2/setup/player/{}/assign-{}",
              "post_v2_setup_player_id_assign_target", "_handle_setup_v2",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/v2/setup/player/[^/]+/delete$",
              "/api/v2/setup/player/{}/delete",
              "post_v2_setup_player_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/player/[^/]+/update$",
              "/api/v2/setup/player/{}/update",
              "post_v2_setup_player_id_update", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/program$", "/api/v2/setup/program",
              "post_v2_setup_program", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/program/[^/]+/assign-\w+$",
              "/api/v2/setup/program/{}/assign-{}",
              "post_v2_setup_program_id_assign_target", "_handle_setup_v2",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/v2/setup/program/[^/]+/delete$",
              "/api/v2/setup/program/{}/delete",
              "post_v2_setup_program_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/rink$", "/api/v2/setup/rink",
              "post_v2_setup_rink", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/rink/[^/]+/assign-\w+$",
              "/api/v2/setup/rink/{}/assign-{}",
              "post_v2_setup_rink_id_assign_target", "_handle_setup_v2",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/v2/setup/rink/[^/]+/delete$",
              "/api/v2/setup/rink/{}/delete", "post_v2_setup_rink_id_delete",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/season$", "/api/v2/setup/season",
              "post_v2_setup_season", "_handle_setup_v2"),
    RouteSpec("POST",
              r"^/api/v2/setup/season-team-registration/[^/]+/assign-division$",
              "/api/v2/setup/season-team-registration/{}/assign-division",
              "post_v2_setup_season_team_registration_id_assign_division",
              "_handle_setup_v2"),
    RouteSpec("POST",
              r"^/api/v2/setup/season-team-registration/[^/]+/assign-league$",
              "/api/v2/setup/season-team-registration/{}/assign-league",
              "post_v2_setup_season_team_registration_id_assign_league",
              "_handle_setup_v2"),
    RouteSpec("POST",
              r"^/api/v2/setup/season-team-registration/[^/]+/delete$",
              "/api/v2/setup/season-team-registration/{}/delete",
              "post_v2_setup_season_team_registration_id_delete",
              "_handle_setup_v2"),
    RouteSpec("POST",
              r"^/api/v2/setup/season-team-registration/[^/]+/remove$",
              "/api/v2/setup/season-team-registration/{}/remove",
              "post_v2_setup_season_team_registration_id_remove",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/season-venue-access/[^/]+/delete$",
              "/api/v2/setup/season-venue-access/{}/delete",
              "post_v2_setup_season_venue_access_id_delete",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/season-venue-access/[^/]+/remove$",
              "/api/v2/setup/season-venue-access/{}/remove",
              "post_v2_setup_season_venue_access_id_remove",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/season/[^/]+/delete$",
              "/api/v2/setup/season/{}/delete",
              "post_v2_setup_season_id_delete", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/seasons/[^/]+/archive$",
              "/api/v2/setup/seasons/{}/archive",
              "post_v2_setup_seasons_id_archive", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/seasons/[^/]+/reopen$",
              "/api/v2/setup/seasons/{}/reopen",
              "post_v2_setup_seasons_id_reopen", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/seasons/[^/]+/roll-forward$",
              "/api/v2/setup/seasons/{}/roll-forward",
              "post_v2_setup_seasons_id_roll_forward", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/seasons/[^/]+/team-registrations$",
              "/api/v2/setup/seasons/{}/team-registrations",
              "post_v2_setup_seasons_id_team_registrations",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/seasons/[^/]+/venue-access$",
              "/api/v2/setup/seasons/{}/venue-access",
              "post_v2_setup_seasons_id_venue_access", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/team$", "/api/v2/setup/team",
              "post_v2_setup_team", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/team/[^/]+/assign-\w+$",
              "/api/v2/setup/team/{}/assign-{}",
              "post_v2_setup_team_id_assign_target", "_handle_setup_v2",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/v2/setup/team/[^/]+/delete$",
              "/api/v2/setup/team/{}/delete", "post_v2_setup_team_id_delete",
              "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/venue$", "/api/v2/setup/venue",
              "post_v2_setup_venue", "_handle_setup_v2"),
    RouteSpec("POST", r"^/api/v2/setup/venue/[^/]+/assign-\w+$",
              "/api/v2/setup/venue/{}/assign-{}",
              "post_v2_setup_venue_id_assign_target", "_handle_setup_v2",
              note=("the target is narrowed downstream by "
                    "_handle_reassign's combo table; the dispatch "
                    "itself accepts any assign-<word>")),
    RouteSpec("POST", r"^/api/v2/setup/venue/[^/]+/delete$",
              "/api/v2/setup/venue/{}/delete",
              "post_v2_setup_venue_id_delete", "_handle_setup_v2"),
)

#: (method, template) -> RouteSpec.
BY_KEY = {spec.key: spec for spec in REGISTRY}
#: name -> RouteSpec.
BY_NAME = {spec.name: spec for spec in REGISTRY}
