# Variables for adw_wallet_rotation.tf
# wallet_password is intentionally removed — the password is now generated by
# random_password.wallet and stored in OCI Vault.

variable "adw_ocid" {
  description = "OCID of the Autonomous Data Warehouse whose wallet is being rotated."
  type        = string
}

variable "is_dedicated" {
  description = "Whether the ADW is on Dedicated infrastructure. Kept for compatibility with the prior module."
  type        = bool
  default     = false
}

variable "compartment_ocid" {
  description = "Compartment that owns the OCI Vault secret."
  type        = string
}

variable "vault_ocid" {
  description = "OCID of the OCI Vault that stores the wallet password secret."
  type        = string
}

variable "key_ocid" {
  description = "OCID of the KMS key used to encrypt the wallet password secret."
  type        = string
}

variable "wallet_secret_name" {
  description = "Name of the OCI Vault secret holding the wallet password."
  type        = string
}

variable "wallet_content_for_di" {
  description = "Optional override wallet content (base64) for downstream Data Integration consumers."
  type        = string
  sensitive   = true
  default     = ""
}
