apiVersion: v1
kind: ConfigMap
metadata:
  name: fa-asset-xfer
  namespace: accounting-gateway
data:
  RUN_ENV: "prod"
  CITADEL_ENV: "prod"
  CA_PEM: "/etc/pki/tls/certs/ca-bundle.crt"
  CA_BUNDLE: "/etc/pki/tls/certs/ca-bundle.crt"
  HTTP_APP_PROXY: "http://appproxy.gtm.citadelgroup.com:80"
  HTTPS_APP_PROXY: "http://appproxy.gtm.citadelgroup.com:80"
  LOG_LEVEL: "INFO"
