apiVersion: v1
kind: ConfigMap
metadata:
  name: fa-asset-xfer
  namespace: accounting-gateway
data:
  LOG_LEVEL: "INFO"
  HTTP_APP_PROXY: "http://webproxy.internal:80"
  HTTPS_APP_PROXY: "http://webproxy.internal:443"
