"""Dataclass models for the roster + substitute domain.

These are plain data holders. All business logic lives in the service layer
so the models stay easy to serialize and test.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Tuple

from .enums import (
    AuditAction,
    AvailabilityStatus,
    GameStatus,
    NotificationType,
    Position,
    RosterEntryStatus,
    RosterRole,
    SelectionSource,
    SlotStatus,
    SlotType,
    SubstituteStatus,
)


@dataclass
class Team:
    id: str
    name: str
    division: str = ""
    club_id: Optional[str] = None
    division_id: Optional[str] = None
    # Idempotency key for the CSV import (#93): the ``team_code`` a repeat
    # upload is matched against, so re-importing updates in place instead of
    # creating duplicates. None for teams created outside the import flow.
    external_ref: Optional[str] = None
    # Permanent owning program (#180/#233, formerly ``league_id``). A team is a
    # permanent member of one program; season-specific division participation
    # lives in SeasonTeamRegistration, not on the Team. Nullable — pre-#180 teams
    # are backfilled from their division's season program by migration 021, and a
    # team created without a division has none until one is derived/assigned.
    program_id: Optional[str] = None
    # Permanent owning League — the hard competition boundary (#283). A Team
    # belongs to exactly one League and may only register (per Season) into that
    # League. Nullable at the model level; migration 034 assigns a permanent
    # league_id to every existing Team (unambiguous mappings automatically; an
    # operator decision for Teams historically registered across multiple
    # Leagues). The invariant ``league.program_id == team.program_id`` (a Team's
    # League and Program agree) is enforced in the service layer.
    league_id: Optional[str] = None


@dataclass
class Player:
    id: str
    team_id: str
    # Flattened DISPLAY name — kept for every legacy consumer. When the
    # structured names below are set it is always derived ("<first> <last>",
    # see domain.identity.derive_display_name), never free-typed (#273).
    name: str
    position: Position
    shoots: Optional[str] = None
    jersey_number: Optional[int] = None
    is_active: bool = True
    # Idempotency key for the CSV import (#93): the ``player_code`` a repeat
    # upload is matched against. None for players created outside the import
    # flow.
    external_ref: Optional[str] = None
    # -- durable athlete identity (#273) --------------------------------
    # Structured names. Nullable: legacy players keep only the flattened
    # ``name`` until an edit/import supplies real parts — migration 058 never
    # guesses a first/last split from the display name.
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    preferred_name: Optional[str] = None
    # PRIVATE birthdate, canonical "YYYY-MM-DD" (a calendar date, no
    # timezone). Stripped from every default facade payload — operators opt
    # in explicitly; ordinary Coach/public payloads never carry it (#273/#124
    # boundary).
    birthdate: Optional[str] = None
    # Stable governing-body registration number (private, same handling as
    # birthdate). The duplicate detector keys on it; it is never a merge key.
    registration_number: Optional[str] = None
    # Existing global/provisional 1-7 skill value. The 2026-08-29 owner ruling
    # on #287 requires the canonical substitute-ranking rating to be scoped to
    # its League context, League-admin-owned, and audited in #273. None =
    # unrated, a fully supported state substitute ranking must degrade on,
    # never exclude.
    skill_rating: Optional[int] = None
    # NOTE (#273): ``guardian_person_id`` is REMOVED from the model/contract.
    # It was serialized but never read or written by any service; the real,
    # verified guardian relationship is ``GuardianLink`` (#26/#35). The DB
    # column is left in place untouched (dropping it is a follow-up
    # migration), so existing rows and the 040 SQLite table rebuild are
    # unaffected.

    @property
    def slot_type(self) -> SlotType:
        return self.position.slot_type


@dataclass
class Game:
    id: str
    home_team_id: str
    start_time: datetime
    target_goalies: int = 1
    target_skaters: int = 15
    max_skaters: int = 18
    away_team_id: Optional[str] = None
    rink: Optional[str] = None
    end_time: Optional[datetime] = None
    roster_lock_time: Optional[datetime] = None
    locked: bool = False
    cancelled: bool = False
    published: bool = False
    season_id: Optional[str] = None
    division_id: Optional[str] = None
    ice_slot_id: Optional[str] = None
    # A draft game generated by the scheduler (#86): never public until it is
    # published (which clears this flag). Distinguishes generated drafts from
    # ordinary unpublished games.
    is_draft: bool = False
    # Owning competition league (#233 Slice C1b). Nullable; backfilled from the
    # game's division league by the reparent migration.
    league_id: Optional[str] = None
    # A Game's competition kind (#283 Slice D): "regular" (counts toward
    # standings, bound to one LeagueSeason — both teams registered in it) or
    # "exhibition" (a friendly that may cross League lines and never affects
    # standings; carries no owning League or Division). Stored as the plain
    # GameType enum string.
    game_type: str = "regular"
    # The exact LeagueSeason a REGULAR game belongs to (#283 Slice E) — its
    # single source of competition identity, so season_id and league_id can
    # never drift apart. NULL for exhibitions (which have no owning
    # LeagueSeason). Backfilled for existing regular games from their unique
    # (league_id, season_id) pair by migration 037.
    league_season_id: Optional[str] = None
    # Immutable cancellation-time ice history (#428).  Cancellation detaches
    # ``ice_slot_id`` so the physical slot becomes reusable/deletable, while
    # these denormalized facts keep the historical fixture intelligible even
    # after #429 later removes the original facility subtree.  They are
    # written once, in the same transaction as cancellation, and never used
    # as current scheduling authority.
    cancelled_ice_slot_id: Optional[str] = None
    cancelled_venue_id: Optional[str] = None
    cancelled_venue_name: Optional[str] = None
    cancelled_venue_timezone: Optional[str] = None
    cancelled_rink_id: Optional[str] = None
    cancelled_rink_name: Optional[str] = None
    cancelled_scheduled_start_time: Optional[datetime] = None
    cancelled_scheduled_end_time: Optional[datetime] = None
    cancelled_ice_start_time: Optional[datetime] = None
    cancelled_ice_end_time: Optional[datetime] = None


@dataclass
class GameRosterEntry:
    id: str
    game_id: str
    player_id: str
    roster_role: RosterRole
    selection_source: SelectionSource
    status: RosterEntryStatus
    selected_at: datetime
    updated_at: datetime
    selected_by: Optional[str] = None
    # ---- DURABLE game-side attribution (#205 blocker 5, migration 061) ----
    # WHAT THIS ROW OCCUPIES, recorded when the row was created or re-seated,
    # from the SAME validated GameMembershipContext that authorized the
    # seating. Round 1 of blocker 5 re-derived both values from the player's
    # CURRENT eligible membership on every read, so a legitimate membership
    # status change erased a seated row's attribution without removing or
    # transitioning the row — the row stayed ACCEPTED and occupying in
    # storage while vanishing from the governed count, and a second player
    # then seated past the target. These columns are the record, not a
    # cache: nothing re-derives them, and only a re-seat rewrites them.
    #
    # ``seated_position`` is stored alongside ``team_side`` because the
    # GOALIE/SKATER bucket had the identical defect (it was read off the
    # live context too), so a row whose context vanished had no bucket at
    # all. For a substitute seating it is the ENROLLMENT's position — the
    # very bucket ``_require_open_slot`` was called with — so the slot the
    # gate checked and the slot the row is counted in are always one slot.
    #
    # Both are NULL for — and only for — rows written before migration 061.
    # See :meth:`attribution` and migration 061 for the fail-closed rule
    # that applies to those, which never guesses a side.
    team_side: Optional[str] = None
    seated_position: Optional[Position] = None

    @property
    def seated_slot_type(self) -> Optional[SlotType]:
        """The durable GOALIE/SKATER bucket, or ``None`` for a pre-061 row."""
        return (None if self.seated_position is None
                else self.seated_position.slot_type)

    @property
    def attribution(self) -> Optional[Tuple[str, SlotType]]:
        """``(team_side, slot_type)`` this row occupies, or ``None`` when the
        row carries no durable attribution at all (pre-061).

        ONE accessor, so slot enforcement and reporting can never read the
        pair from two different places and disagree about what a seated row
        holds. Treats a half-written pair as unattributed: the two columns
        are only ever written together, so one of them missing is not a
        partial answer to be salvaged."""
        if self.team_side is None or self.seated_position is None:
            return None
        return self.team_side, self.seated_position.slot_type


@dataclass
class GameAvailability:
    id: str
    game_id: str
    player_id: str
    availability_status: AvailabilityStatus
    response_source: str = "player"
    responded_at: Optional[datetime] = None
    notes: Optional[str] = None


@dataclass
class SubstituteEnrollment:
    id: str
    game_id: str
    player_id: str
    position: Position
    status: SubstituteStatus
    enrolled_at: datetime
    priority_rank: Optional[int] = None
    offered_at: Optional[datetime] = None
    offer_expires_at: Optional[datetime] = None
    accepted_at: Optional[datetime] = None
    declined_at: Optional[datetime] = None
    # #205: THE ENROLLMENT'S OWNING TEAM — the side this row was admitted
    # on, snapshotted from the SAME GameMembershipContext that authorized
    # the transition, at the moment that context was genuinely valid (the
    # pattern `position` above already established: resolve once, store it).
    #
    # WRITTEN TWICE, ONE FIELD, TWO PHASES, and each phase's value is the
    # authority for that phase:
    #
    #   ENROLLED — written by `enroll_substitute` from the context its
    #     eligibility gate accepted (owner ruling, PR #427, comment
    #     5391127041). This is what makes an ENROLLED row's owner
    #     answerable at all: before it, `team_id` was NULL until an offer
    #     was made, so `withdraw_substitute` had NO durable side to
    #     authorize a Coach against and would have had to re-resolve
    #     membership live — which is exactly the substitution the ruling
    #     forbids, because it hands a row to whichever coach the player
    #     happens to belong to NOW rather than the one who owns the row.
    #
    #   OFFERED — REPLACED by `offer_substitute` with the side IT validated
    #     the offer against. "Once OFFERED, the existing offer-owner
    #     snapshot remains authoritative for that phase" (same ruling), so
    #     the offer phase keeps the #205 blocker-3 contract below unchanged.
    #
    # #205 blocker 3: FOR AN OFFER, this is THE OFFER'S OWNING TEAM —
    #
    # AUTHORITATIVE FOR THE OFFER'S WHOLE LIFETIME. decline_substitute
    # addresses its coach notification from this value and ONLY this value:
    # decline is the terminal response to an already-issued offer, so its
    # audience is whoever OWNS that offer, never a team re-resolved at
    # decline time (which, after a reassignment or a transfer, is the
    # OPPONENT — see roster_service.decline_substitute and
    # 060_substitute_team_id.sql for why accept's live re-resolution is not
    # a precedent here). It is also durable by construction, so a membership
    # ending after the offer can no longer make that audience_ref come back
    # None and crash the decline.
    #
    # NULL ONLY FOR LEGACY ROWS — any row enrolled/offered before migration
    # 060, and any row enrolled before the Part A change above. Migration
    # 060 is additive with NO backfill and Part A adds none either: there is
    # no honest historical source to backfill FROM, and `Player.team_id` /
    # current membership answer a DIFFERENT question than "which side was
    # this row admitted on" (owner ruling: "Legacy enrollment attribution
    # must remain honest: do not backfill from `Player.team_id` or current
    # membership"). The column stays nullable and legacy rows stay NULL.
    #
    # A NULL therefore means "this row cannot name its owner", and every
    # consumer fails closed on it in its own way: decline_substitute commits
    # and SUPPRESSES its targeted push rather than guessing an audience, and
    # a COACH acting on such a row is refused `attribution_missing` with
    # zero writes (RosterService._require_authorized_team). Player
    # self-service and an unscoped League Admin are unaffected — their
    # authority never came from this column.
    team_id: Optional[str] = None

    @property
    def slot_type(self) -> SlotType:
        return self.position.slot_type


@dataclass
class AuditLog:
    id: str
    game_id: str
    action: AuditAction
    at: datetime
    actor_id: Optional[str] = None
    subject_player_id: Optional[str] = None
    detail: dict = field(default_factory=dict)


@dataclass
class NotificationEvent:
    id: str
    game_id: str
    type: NotificationType
    audience: str  # "coach" | "player" | "guardian" | "team"
    message: str
    at: datetime
    subject_player_id: Optional[str] = None


@dataclass
class SlotSummary:
    slot_type: SlotType
    target_count: int
    confirmed_count: int
    occupied_count: int
    open_count: int
    substitutes_available: int
    status: SlotStatus


@dataclass
class RosterStatus:
    game_id: str
    team_id: str
    target_goalies: int
    confirmed_goalies: int
    open_goalie_slots: int
    target_skaters: int
    confirmed_skaters: int
    open_skater_slots: int
    substitutes_enrolled: int
    status: GameStatus
    action_required: bool
    message: str

    def to_dict(self) -> dict:
        return {
            "game_id": self.game_id,
            "team_id": self.team_id,
            "target_goalies": self.target_goalies,
            "confirmed_goalies": self.confirmed_goalies,
            "open_goalie_slots": self.open_goalie_slots,
            "target_skaters": self.target_skaters,
            "confirmed_skaters": self.confirmed_skaters,
            "open_skater_slots": self.open_skater_slots,
            "substitutes_enrolled": self.substitutes_enrolled,
            "status": self.status.value,
            "action_required": self.action_required,
            "message": self.message,
        }
